In [29]:
#numpy basics

In [5]:
import numpy as np

In [6]:
mylist = [1,2,3]

In [7]:
type(mylist)

list

In [8]:
myarray = np.array(mylist)

In [9]:
myarray

array([1, 2, 3])

In [10]:
type(myarray)

numpy.ndarray

In [12]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [14]:
np.zeros(shape=(10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones(shape=(2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.random.seed(101)
arr = np.random.randint(0,100,10)

In [18]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [19]:
arr2 =np.random.randint(0,100,10)

In [20]:
arr2

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [21]:
#max value of array
arr.max()

95

In [22]:
arr.argmax()

0

In [23]:
#min value
arr.min()

9

In [24]:
arr.argmin()

7

In [25]:
arr.mean()

60.8

In [27]:
#reshape arrays
arr.shape

(10,)

In [28]:
arr.reshape((2,5))

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [33]:
#matrix
mat = np.arange(0,100).reshape(10,10)

In [34]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [35]:
row = 0
col = 1

In [36]:
mat[row,col]

1

In [37]:
#grab a specific number (57)
row = 5
col = 7

In [38]:
mat[row,col]

57

In [40]:
#slicing
#everything in a column
mat[:,1]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [42]:
#slice and reshape
mat[:,1].reshape(10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [43]:
#reshape column

In [44]:
mat[:,1].reshape(10,1)

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [45]:
#slice row
mat[2,:]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [48]:
#more slicing rows and columns
# same as normal python slicing notation
mat[0:3,0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [49]:
# reassign some values in matrix
mat[0:3,0:3] = 0

In [50]:
mat

array([[ 0,  0,  0,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  0,  0, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  0,  0, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [51]:
# or reassign values in a copy of matrix
mynewmat = mat.copy()

In [56]:
# example change values in first 6 rows to 999
mynewmat[0:6,:] = 999

In [57]:
mynewmat

array([[999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]])